language: python
python:
  - 3.7
before_install:
  - python --version
  - pip install -U pip
  - python -m pip install -r requirements.txt
script:
  - pytest
notifications:
  email:
    recipients:
      - ur@email.com
    on_success: never
    on_failure: always
