language: python
python:
  - 3.7
script:
  - pytest
virtualenv:
  system_site_packages: true
- stage: test
  os: osx
  language: sh
  env: TOXENV=py3
  addons:
    homebrew:
      update: true
      packages: python3
  before_install:
    - pip3 install virtualenv
    - virtualenv -p python3 ~/venv
    - source ~/venv/bin/activate
notifications:
  email:
    recipients:
      - ur@email.com
    on_success: never
    on_failure: always
