language: python
python:
  - 3.7
script:
  - pytest
os:
  - osx
osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
virtualenv:
  system_site_packages: true
notifications:
  email:
    recipients:
      - ur@email.com
    on_success: never
    on_failure: always
